### ISSUE TITLE
Why does withAnyCase() add the 'm' flag along with the 'i' flag

### ISSUE THREAD

**Issue by st-clair-clarke** [VerbalExpressions/DartVerbalExpressions#3]
Hi,
I have the following 
RegExp alphaMatcher = new VerbalExpression( ).startOfLine( ).add( 'a-'
    'z' ).oneOrMore( ).withAnyCase(true).anyOf( "' -" ).zeroOrMore( )
    .endOfLine( )
    .toRegExp( );

// PLEASE LOOK AT THE RESULT
String alphaPattern = alphaMatcher.toString( ); // JSRegExp: pattern=^a-z+[\'\ -]*$ flags=im

I think because of that the following test fails. 

class WordTests {
  static run( ) {
    group( 'Language Words', ( ) {
      VerbalExpression exp;

```
  setUp( ( ) {
    exp = new VerbalExpression( );
  } );

  test( '-> should return correct word match', ( ) {
    expect( alphaMatcher.hasMatch( 'Teddy' ), isTrue,
        reason: 'Word | upper and lower case' );
  } );
} );
```

  }
}

void main( ) {
  WordTests.run( );
}

**Comment by Ne4istb** [comment]
@st-clair-clarke 
As this library is a port from JS version I've taken multiline search as default, the same as there. Probably, have to mention it in the documentation. But multiline search works fine for a single line as well.

The actual problem is in your expression: add() method should be used to add another regular expression into the current. If you want to specify some range, please, use 
- either range() method (in your case 

``` dart
.range([new Range('a','z')]) 
```
- or pass correct regex into the pipeline (in your case 

``` dart
.add('[a-z]')
```

**Comment by st-clair-clarke** [comment]
Thanks Phillip. It now works. Your library brings a lot of fun back to regex.

**Comment by st-clair-clarke** [comment]
Thanks Andri. It now works. Your library brings a lot of fun back to regex.
